#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source ${THIS_DIR}/env-variables

function ensure_exists() {
  echo "ensure directory $1 exists"
  if [ ! -d ${1} ]; then
    mkdir -p ${1}
  fi
}

case "$1" in
  ensure_exists)
    ensure_exists ${WORKDIR}
    ;;
  ensure_images_dir_exists)
    ensure_exists ${IMAGES_DIR}
    ;;
  ensure_certs_and_configs_dir_exists)
    ensure_exists ${CERTS_AND_CONFIGS_DIR}
    ;;
  ensure_tools_dir_exists)
    ensure_exists ${TOOLS_DIR}
    ;;
  ensure_vm_configs_dir_exists)
    ensure_exists ${VM_CONFIGS_DIR}
    ;;
  *)
    echo "Usage: $0 {WORKDIR='./work' ensure_exists|ensure_images_dir_exists|ensure_certs_and_configs_dir_exists|ensure_tools_dir_exists}"
esac
